data_params:
  data_path: 'celeba/'
  batch_size: 32
  num_workers: 16
  pin_memory: True

model_params:
  channels: 3
  latent_dim: 200
  critic_steps: 3

training_params:
  lr: 0.0002
  max_epochs: 30

hardware_params:
  accelerator: 'auto'
  devices: 1