data_params:
  data_path: 'celeba/'
  batch_size: 32
  num_workers: 16
  pin_memory: True

model_params:
  in_channels: 3
  z_dim: 512

training_params:
  lr: 0.0002
  max_epochs: 30

hardware_params:
  accelerator: 'auto'
  devices: 1