data_params:
  data_path: 'celeba/'
  batch_size: 256
  num_workers: 16
  pin_memory: True

model_params:
  channels: 3
  latent_dim: 128
  critic_steps: 4

training_params:
  lr: 0.0001
  max_epochs: 100

hardware_params:
  accelerator: 'auto'
  devices: 1